language: ruby
gemfile:
  - gemfiles/Gemfile.travis
rvm:
  - 2.1.1
  - 2.1.6
  - 2.1.7
  - 2.1.8
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.2.5
  - 2.2.6
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.4.0
  - 2.4.1
sudo: false
notifications:
  email:
    recipients:
      - rdl-devel@googlegroups.com
    on_success: never # default: change
    on_failure: always # default: always
