language: ruby
gemfile:
  - gemfiles/Gemfile.travis
rvm:
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - 2.5.5
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.7.0
notifications:
  email:
    recipients:
      - rdl-devel@googlegroups.com
    on_success: never # default: change
    on_failure: always # default: always
