rdl_nowrap :Array

class Array
  type_params [:t], :all?
end

type :Array, :<<, '(t) -> Array<t>'
type :Array, :[], '(Range<Integer>) -> Array<t>'
type :Array, :[], '(Integer or Float) -> t'
type :Array, :[], '(Integer, Integer) -> Array<t>'
type :Array, :&, '(Array<u>) -> Array<t>'
type :Array, :*, '(Integer) -> Array<t>'
type :Array, :*, '(String) -> String'
type :Array, :+, '(Enumerable<u>) -> Array<u or t>'
type :Array, :+, '(Array<u>) -> Array<u or t>'
type :Array, :-, '(Array<u>) -> Array<u or t>'
type :Array, :slice, '(Range<Integer>) -> Array<t>'
type :Array, :slice, '(Integer) -> t'
type :Array, :slice, '(Integer, Integer) -> Array<t>'
type :Array, :[]=, '(Integer, t) -> t'
type :Array, :[]=, '(Integer, Integer, t) -> t'
# type :Array, :[]=, '(Integer, Integer, Array<t>) -> Array<t>'
# type :Array, :[]=, '(Range, Array<t>) -> Array<t>'
type :Array, :[]=, '(Range<Integer>, t) -> t'
type :Array, :assoc, '(t) -> Array<t>'
type :Array, :at, '(Integer) -> t'
type :Array, :clear, '() -> Array<t>'
type :Array, :map, '() {(t) -> u} -> Array<u>'
type :Array, :map, '() -> Enumerator<t>'
type :Array, :map!, '() {(t) -> u} -> Array<u>'
type :Array, :map!, '() -> Enumerator<t>'
type :Array, :collect, '() { (t) -> u } -> Array<u>'
type :Array, :collect, '() -> Enumerator<t>'
type :Array, :combination, '(Integer) { (Array<t>) -> %any } -> Array<t>'
type :Array, :combination, '(Integer) -> Enumerator<t>'
type :Array, :push, '(*t) -> Array<t>'
type :Array, :compact, '() -> Array<t>'
type :Array, :compact!, '() -> Array<t>'
type :Array, :concat, '(Array<t>) -> Array<t>'
type :Array, :count, '() -> Integer'
type :Array, :count, '(t) -> Integer'
type :Array, :count, '() { (t) -> %bool } -> Integer'
type :Array, :cycle, '(?Integer) { (t) -> %any } -> %any'
type :Array, :cycle, '(?Integer) -> Enumerator<t>'
type :Array, :delete, '(u) -> t'
type :Array, :delete, '(u) { () -> v } -> t or v'
type :Array, :delete_at, '(Integer) -> Array<t>'
type :Array, :delete_if, '() { (t) -> %bool } -> Array<t>'
type :Array, :delete_if, '() -> Enumerator<t>'
type :Array, :drop, '(Integer) -> Array<t>'
type :Array, :drop_while, '() { (t) -> %bool } -> Array<t>'
type :Array, :drop_while, '() -> Enumerator<t>'
type :Array, :each, '() -> Enumerator<t>'
type :Array, :each, '() { (t) -> %any } -> Array<t>'
type :Array, :each_index, '() { (Integer) -> %any } -> Array<t>'
type :Array, :each_index, '() -> Enumerator<t>'
type :Array, :empty?, '() -> %bool'
type :Array, :fetch, '(Integer) -> t'
type :Array, :fetch, '(Integer, u) -> u'
type :Array, :fetch, '(Integer) { (Integer) -> u } -> t or u'
type :Array, :fill, '(t) -> Array<t>'
type :Array, :fill, '(t, Integer, ?Integer) -> Array<t>'
type :Array, :fill, '(t, Range<Integer>) -> Array<t>'
type :Array, :fill, '() { (Integer) -> t } -> Array<t>'
type :Array, :fill, '(Integer, ?Integer) { (Integer) -> t } -> Array<t>'
type :Array, :fill, '(Range<Integer>) { (Integer) -> t } -> Array<t>'
type :Array, :flatten, '() -> Array<%any>' # Can't give a more precise type
type :Array, :index, '(u) -> Integer'
type :Array, :index, '() { (t) -> %bool } -> Integer'
type :Array, :index, '() -> Enumerator<t>'
type :Array, :first, '() -> t'
type :Array, :first, '(Integer) -> Array<t>'
type :Array, :include?, '(u) -> %bool'
type :Array, :initialize, '() -> self'
type :Array, :initialize, '(Integer) -> self'
type :Array, :initialize, '(Integer, t) -> self'
type :Array, :insert, '(Integer, *t) -> Array<t>'
type :Array, :inspect, '() -> String'
type :Array, :join, '(?String) -> String'
type :Array, :keep_if, '() { (t) -> %bool } -> Array<t>'
type :Array, :last, '() -> t'
type :Array, :last, '(Integer) -> Array<t>'
type :Array, :member, '(u) -> %bool'
type :Array, :length, '() -> Integer'
type :Array, :permutation, '(?Integer) -> Enumerator<t>'
type :Array, :permutation, '(?Integer) { (Array<t>) -> %any } -> Array<t>'
type :Array, :pop, '(Integer) -> Array<t>'
type :Array, :pop, '() -> t'
type :Array, :product, '(*Array<u>) -> Array<Array<t or u>>'
type :Array, :rassoc, '(u) -> t'
type :Array, :reject, '() { (t) -> %bool } -> Array<t>'
type :Array, :reject, '() -> Enumerator<t>'
type :Array, :reject!, '() { (t) -> %bool } -> Array<t>'
type :Array, :reject!, '() -> Enumerator<t>'
type :Array, :repeated_combination, '(Integer) { (Array<t>) -> %any } -> Array<t>'
type :Array, :repeated_combination, '(Integer) -> Enumerator<t>'
type :Array, :repeated_permutation, '(Integer) { (Array<t>) -> %any } -> Array<t>'
type :Array, :repeated_permutation, '(Integer) -> Enumerator<t>'
type :Array, :reverse, '() -> Array<t>'
type :Array, :reverse!, '() -> Array<t>'
type :Array, :reverse_each, '() { (t) -> %any } -> Array<t>'
type :Array, :reverse_each, '() -> Enumerator<t>'
type :Array, :rindex, '(u) -> t'
type :Array, :rindex, '() { (t) -> %bool } -> Integer'
type :Array, :rindex, '() -> Enumerator<t>'
type :Array, :rotate, '(?Integer) -> Array<t>'
type :Array, :rotate!, '(?Integer) -> Array<t>'
type :Array, :sample, '() -> t'
type :Array, :sample, '(Integer) -> Array<t>'
type :Array, :select, '() { (t) -> %bool } -> Array<t>'
type :Array, :select, '() -> Enumerator<t>'
type :Array, :select!, '() { (t) -> %bool } -> Array<t>'
type :Array, :select!, '() -> Enumerator<t>'
type :Array, :shift, '() -> t'
type :Array, :shift, '(Integer) -> Array<t>'
type :Array, :shuffle, '() -> Array<t>'
type :Array, :shuffle!, '() -> Array<t>'
rdl_alias :Array, :size, :length
rdl_alias :Array, :slice, :[]
type :Array, :slice!, '(Range<Integer>) -> Array<t>'
type :Array, :slice!, '(Integer, Integer) -> Array<t>'
type :Array, :slice!, '(Integer or Float) -> t'
type :Array, :sort, '() -> Array<t>'
type :Array, :sort, '() { (t,t) -> Integer } -> Array<t>'
type :Array, :sort!, '() -> Array<t>'
type :Array, :sort!, '() { (t,t) -> Integer } -> Array<t>'
type :Array, :sort_by!, '() { (t) -> u } -> Array<t>'
type :Array, :sort_by!, '() -> Enumerator<t>'
type :Array, :take, '(Integer) -> Array<t>'
type :Array, :take_while, '() { (t) ->%bool } -> Array<t>'
type :Array, :take_while, '() -> Enumerator<t>'
type :Array, :to_a, '() -> Array<t>'
type :Array, :to_ary, '() -> Array<t>'
rdl_alias :Array, :to_s, :inspect
type :Array, :transpose, '() -> Array<t>'
type :Array, :uniq, '() -> Array<t>'
type :Array, :uniq!, '() -> Array<t>'
type :Array, :unshift, '(*t) -> Array<t>'
type :Array, :values_at, '(*Range<Integer> or Integer) -> Array<t>'
type :Array, :zip, '(*Array<u>) -> Array<Array<t or u>>'
type :Array, :|, '(Array<u>) -> Array<t or u>'
