rdl_nowrap :MatchData

type :MatchData, :==, '(%any) -> %bool'
type :MatchData, :[], '(Fixnum i) -> String or nil'
type :MatchData, :[], '(Fixnum start, Fixnum length) -> Array<String>'
type :MatchData, :[], '(Range<Fixnum> range) -> Array<String>'
type :MatchData, :[], '(String or Symbol name) -> String or nil'
type :MatchData, :begin, '(Fixnum n) -> Fixnum'
type :MatchData, :captures, '() -> Array<String>'
type :MatchData, :end, '(Fixnum n) -> Fixnum'
type :MatchData, :eql?, '(%any other) -> %bool'
type :MatchData, :hash, '() -> Fixnum'
type :MatchData, :inspect, '() -> String'
type :MatchData, :length, '() -> Fixnum'
type :MatchData, :names, '() -> Array<String>'
type :MatchData, :offset, '(Fixnum n) -> Array<Fixnum>'
type :MatchData, :post_match, '() -> String'
type :MatchData, :pre_match, '() -> String'
type :MatchData, :regexp, '() -> Regexp'
type :MatchData, :size, '() -> Fixnum'
type :MatchData, :string, '() -> String'
type :MatchData, :to_a, '() -> Array<String>'
type :MatchData, :to_s, '() -> String'
type :MatchData, :values_at, '(*Fixnum indexes) -> Array<String>'
