rdl_nowrap :Numeric

type :Numeric, :%, '(%numeric) -> %numeric'
pre(:Numeric, :%) { |x| x!=0}
type :Numeric, :+, '(%numeric) -> %numeric'
type :Numeric, :-, '() -> %numeric'
type :Numeric, :-@, '() -> %numeric'
type :Numeric, :+@, '() -> %numeric'
type :Numeric, :<=>, '(%numeric) -> Object'
post(:Numeric, :<=>) { |r,x| r == -1 || r==0 || r==1 || r==nil}
type :Numeric, :abs, '() -> %numeric'
post(:Numeric, :abs) { |r,x| r >= 0 }
type :Numeric, :abs2, '() -> %numeric'
post(:Numeric, :abs2) { |r,x| r >= 0 }
type :Numeric, :angle, '() -> %numeric'
type :Numeric, :arg, '() -> %numeric'
type :Numeric, :ceil, '() -> Integer'
type :Numeric, :coerce, '(%numeric) -> [%numeric, %numeric]'
type :Numeric, :conj, '() -> %numeric'
type :Numeric, :conjugate, '() -> %numeric'
type :Numeric, :denominator, '() -> Integer'
post(:Numeric, :denominator) { |r,x| r >= 0 }
type :Numeric, :div, '(%numeric) -> Integer'
pre(:Numeric, :div) { |x| x!=0}
type :Numeric, :divmod, '(%numeric) -> [%numeric, %numeric]'
pre(:Numeric, :divmod) { |x| x!=0 }
type :Numeric, :eql?, '(%numeric) -> %bool'
type :Numeric, :fdiv, '(%numeric) -> %numeric'
type :Numeric, :floor, '() -> Integer'
type :Numeric, :i, '() -> Complex'
type :Numeric, :imag, '() -> %numeric'
type :Numeric, :imaginary, '() -> %numeric'
type :Numeric, :integer?, '() -> %bool'
type :Numeric, :magnitude, '() -> %numeric'
type :Numeric, :modulo, '(%numeric) -> %real'
pre(:Numeric, :modulo) { |x| x!=0 }
type :Numeric, :nonzero?, '() -> self or nil'
type :Numeric, :numerator, '() -> Integer'
type :Numeric, :phase, '() -> %numeric'
type :Numeric, :polar, '() -> [%numeric, %numeric]'
type :Numeric, :quo, '(%numeric) -> %numeric'
type :Numeric, :real, '() -> %numeric'
type :Numeric, :real?, '() -> %numeric'
type :Numeric, :rect, '() -> [%numeric, %numeric]'
type :Numeric, :rectangular, '() -> [%numeric, %numeric]'
type :Numeric, :remainder, '(%numeric) -> %real'
type :Numeric, :round, '(%numeric) -> %numeric'
type :Numeric, :singleton_method_added, '(Symbol) -> TypeError'
type :Numeric, :step, '(%numeric) { (%numeric) -> %any } -> %numeric'
type :Numeric, :step, '(%numeric) -> Enumerator<%numeric>'
type :Numeric, :step, '(%numeric, %numeric) { (%numeric) -> %any } -> %numeric'
type :Numeric, :step, '(%numeric, %numeric) -> Enumerator<%numeric>'
type :Numeric, :to_c, '() -> Complex'
type :Numeric, :to_int, '() -> Integer'
type :Numeric, :truncate, '() -> Integer'
type :Numeric, :zero?, '() -> %bool'
