rdl_nowrap :Process

type :Process, 'self.abort', '(?String msg) -> %any'
type :Process, 'self.argv0', '() -> String frozen_string'
type :Process, 'self.clock_getres', '(Symbol or Fixnum clock_id, ?Symbol unit) -> Float or Integer'
type :Process, 'self.clock_gettime', '(Symbol or Fixnum clock_id, ?Symbol unit) -> Float or Integer'
type :Process, 'self.daemon', '(?%any nochdir, ?%any noclose) -> 0'
type :Process, 'self.detach', '(Fixnum pid) -> Thread'
type :Process, 'self.egid', '() -> Fixnum'
type :Process, 'self.egid=', '(Fixnum) -> Fixnum'
type :Process, 'self.euid', '() -> Fixnum'
type :Process, 'self.euid=', '(Fixnum) -> Fixnum user'
  #type :Process, 'self.exec', '(env: ?Hash<String, String>, command:String, args:*String) -> %any' # TODO: env
type :Process, 'self.exit', '(?Fixnum status) -> %any'
type :Process, 'self.exit!', '(?Fixnum status) -> %any'
type :Process, 'self.fork', '() -> Fixnum or nil'
type :Process, 'self.fork', '() { () -> %any } -> Fixnum or nil'
type :Process, 'self.getpgid', '(Fixnum pid) -> Fixnum'
type :Process, 'self.getpgrp', '() -> Fixnum'
type :Process, 'self.getpriority', '(Fixnum kind, Fixnum) -> Fixnum'
type :Process, 'self.getrlimit', '(Symbol or String or Fixnum resource) -> [Fixnum, Fixnum] cur_max_limit'
type :Process, 'self.getsid', '(?Fixnum pid) -> Integer'
type :Process, 'self.gid', '() -> Fixnum'
type :Process, 'self.gid=', '(Fixnum) -> Fixnum'
type :Process, 'self.groups', '() -> Array<Fixnum>'
type :Process, 'self.groups=', '(Array<Fixnum>) -> Array<Fixnum>'
type :Process, 'self.initgroups', '(String username, Fixnum gid) -> Array<Fixnum>'
type :Process, 'self.kill', '(Fixnum or Symbol or String signal, *Fixnum pids) -> Fixnum'
type :Process, 'self.maxgroups', '() -> Fixnum'
type :Process, 'self.maxgroups=', '(Fixnum) -> Fixnum'
type :Process, 'self.pid', '() -> Fixnum'
type :Process, 'self.ppid', '() -> Fixnum'
type :Process, 'self.pgid', '(Fixnum pid, Fixnum) -> Fixnum'
type :Process, 'self.setpriority', '(Fixnum kind, Fixnum, Fixnum priority) -> 0'
type :Process, 'self.setproctitle', '(String) -> String'
type :Process, 'self.setrlimit', '(Symbol or String or Fixnum resource, Fixnum cur_limit, ?Fixnum max_limit) -> nil'
type :Process, 'self.setsid', '() -> Fixnum'
  #type :Process, 'self.spawn', '(?Hash<String, String> env, String command, *String args) -> %any' # TODO: env
type :Process, 'self.times', '() -> Process::Tms'
type :Process, 'self.uid', '() -> Fixnum'
type :Process, 'self.uid=', '(Fixnum user) -> Fixnum'
type :Process, 'self.wait', '(?Fixnum pid, ?Fixnum flags) -> Fixnum'
type :Process, 'self.wait2', '(?Fixnum pid, ?Fixnum flags) -> [Fixnum, Fixnum] pid_and_status'
type :Process, 'self.waitall', '() -> Array<[Fixnum, Fixnum]>'
type :Process, 'self.waitpid', '(?Fixnum pid, ?Fixnum flags) -> Fixnum'
type :Process, 'self.waitpid2', '(?Fixnum pid, ?Fixnum flags) -> [Fixnum, Fixnum] pid_and_status'

rdl_nowrap :'Process::GID'
type :'Process::GID', 'self.change_privilege', '(Fixnum group) -> Fixnum'
type :'Process::GID', 'self.eid', '() -> Fixnum'
type :'Process::GID', 'self.from_name', '(String name) -> Fixnum gid'
type :'Process::GID', 'self.grant_privilege', '(Fixnum group) -> Fixnum'
rdl_alias :'Process::GID', 'self.eid=', 'self.grant_privilege'
type :'Process::GID', 'self.re_exchange', '() -> Fixnum'
type :'Process::GID', 'self.re_exchangeable?', '() -> %bool'
type :'Process::GID', 'self.rid', '() -> Fixnum'
type :'Process::GID', 'self.sid_available?', '() -> %bool'
type :'Process::GID', 'self.switch', '() -> Fixnum'
type :'Process::GID', 'self.switch', '() { () -> t } -> t'

rdl_nowrap :'Process::UID'
type :'Process::UID', 'self.change_privilege', '(Fixnum user) -> Fixnum'
type :'Process::UID', 'self.eid', '() -> Fixnum'
type :'Process::UID', 'self.from_name', '(String name) -> Fixnum uid'
type :'Process::UID', 'self.grant_privilege', '(Fixnum user) -> Fixnum'
rdl_alias :'Process::UID', 'self.eid=', 'self.grant_privilege'
type :'Process::UID', 'self.re_exchange', '() -> Fixnum'
type :'Process::UID', 'self.re_exchangeable?', '() -> %bool'
type :'Process::UID', 'self.rid', '() -> Fixnum'
type :'Process::UID', 'self.sid_available?', '() -> %bool'
type :'Process::UID', 'self.switch', '() -> Fixnum'
type :'Process::UID', 'self.switch', '() { () -> t } -> t'

rdl_nowrap :'Process::Status'
 type :'Process::Status', :&, '(Fixnum num) -> Fixnum'
 type :'Process::Status', :==, '(%any other) -> %bool'
 type :'Process::Status', :>>, '(Fixnum num) -> Fixnum'
 type :'Process::Status', :coredump?, '() -> %bool'
 type :'Process::Status', :exited?, '() -> %bool'
 type :'Process::Status', :exitstatus, '() -> Fixnum or nil'
 type :'Process::Status', :inspect, '() -> String'
 type :'Process::Status', :pid, '() -> Fixnum'
 type :'Process::Status', :signaled?, '() -> %bool'
 type :'Process::Status', :stopped?, '() -> %bool'
 type :'Process::Status', :stopsig, '() -> Fixnum or nil'
 type :'Process::Status', :success?, '() -> %bool'
 type :'Process::Status', :termsig, '() -> Fixnum or nil'
 type :'Process::Status', :to_i, '() -> Fixnum'
rdl_alias :'Process::Status', :to_int, :to_i
type :'Process::Status', :to_s, '() -> String'

rdl_nowrap :'Process::Sys'
type :'Process::Sys', 'self.geteid', '() -> Fixnum'
type :'Process::Sys', 'self.geteuid', '() -> Fixnum'
type :'Process::Sys', 'self.getgid', '() -> Fixnum'
type :'Process::Sys', 'self.getuid', '() -> Fixnum'
type :'Process::Sys', 'self.issetugid', '() -> %bool'
type :'Process::Sys', 'self.setegid', '(Fixnum group) -> nil'
type :'Process::Sys', 'self.seteuid', '(Fixnum user) -> nil'
type :'Process::Sys', 'self.setgid', '(Fixnum group) -> nil'
type :'Process::Sys', 'self.setregid', '(Fixnum rid, Fixnum eid) -> nil'
type :'Process::Sys', 'self.setresgid', '(Fixnum rid, Fixnum eid, Fixnum sid) -> nil'
type :'Process::Sys', 'self.setresuid', '(Fixnum rid, Fixnum eid, Fixnum sid) -> nil'
type :'Process::Sys', 'self.setreuid', '(Fixnum rid, Fixnum eid) -> nil'
type :'Process::Sys', 'self.setrgid', '(Fixnum group) -> nil'
type :'Process::Sys', 'self.setruid', '(Fixnum user) -> nil'
type :'Process::Sys', 'self.setuid', '(Fixnum user) -> nil'

rdl_nowrap :'Process::Waiter'
type :'Process::Waiter', 'pid', '() -> Fixnum'
