RDL.nowrap :'ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :beginning_of_day, '() -> ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :end_of_day, '() -> ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :beginning_of_week, '() -> ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :end_of_week, '() -> ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :to_date, '() -> Date'
RDL.type :'ActiveSupport::TimeWithZone', :strftime, '(String) -> String'
RDL.type :'ActiveSupport::TimeWithZone', :+, '(ActiveSupport::Duration) -> ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :-, '(ActiveSupport::Duration) -> ActiveSupport::TimeWithZone'
RDL.type :'ActiveSupport::TimeWithZone', :<, '(ActiveSupport::TimeWithZone or Time) -> %bool'
RDL.type :'ActiveSupport::TimeWithZone', :>, '(ActiveSupport::TimeWithZone or Time) -> %bool'
RDL.type :'ActiveSupport::TimeWithZone', :<=, '(ActiveSupport::TimeWithZone or Time) -> %bool'
RDL.type :'ActiveSupport::TimeWithZone', :>=, '(ActiveSupport::TimeWithZone or Time) -> %bool'
