#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


module RDL::Type

class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 162)

def initialize()
  @yydebug = true
end

...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    21,    71,    19,    20,    72,    22,    29,    32,    14,    16,
    41,    73,    11,    69,    17,    62,    18,    77,    33,    13,
    31,    34,    21,    31,    19,    20,    75,    22,    29,    32,
    14,    16,    76,    40,    11,    40,    17,    62,    18,    78,
    33,    13,    31,    34,    45,    79,    43,    44,     5,     6,
    45,    41,    43,    44,    46,    83,     7,    41,    80,    84,
    46,    81,     7,    67,    48,    87,    21,    65,    19,    20,
    48,    22,    60,    15,    14,    16,    59,    93,    11,    58,
    17,    21,    18,    19,    20,    13,    22,    57,    15,    14,
    16,    96,    56,    11,    40,    17,    21,    18,    19,    20,
    13,    22,     7,    15,    14,    16,    38,   101,    11,     7,
    17,    21,    18,    19,    20,    13,    22,   103,    51,    14,
    16,    36,   105,    11,   106,    17,     7,    18,    55,    21,
    13,    19,    20,   108,    22,     7,    15,    14,    16,     8,
   111,   113,   114,    17,    21,    18,    19,    20,    13,    22,
    77,    15,    14,    16,    70,   115,   nil,   nil,    17,    21,
    18,    19,    20,    13,    22,   nil,    15,    14,    16,   nil,
   nil,   nil,   nil,    17,    21,    18,    19,    20,    13,    22,
   nil,    15,    14,    16,   nil,   nil,   nil,   nil,    17,    21,
    18,    19,    20,    13,    22,   nil,    15,    14,    16,   nil,
   nil,    11,   nil,    17,   nil,    18,   nil,    90,    13,    21,
   nil,    19,    20,   nil,    22,   nil,    15,    14,    16,   nil,
   nil,    11,   nil,    17,    21,    18,    19,    20,    13,    22,
   nil,    15,    14,    16,   nil,   nil,    11,   nil,    17,    21,
    18,    19,    20,    13,    22,   nil,    15,    14,    16,   nil,
   nil,   nil,   nil,    17,    21,    18,    19,    20,    13,    22,
   nil,    15,    14,    16,   nil,   nil,    11,   nil,    17,    21,
    18,    19,    20,    13,    22,   nil,    15,    14,    16,   nil,
   nil,    11,   nil,    17,    21,    18,    19,    20,    13,    22,
   nil,    15,    14,    16,   nil,   nil,    11,   nil,    17,    21,
    18,    19,    20,    13,    22,   nil,    15,    14,    16,   nil,
   nil,    11,   nil,    17,    21,    18,    19,    20,    13,    22,
   nil,    15,    14,    16,   nil,   nil,   nil,   nil,    17,    21,
    18,    19,    20,    13,    22,   nil,    15,    14,    16,   nil,
   nil,    11,   nil,    17,    21,    18,    19,    20,    13,    22,
   nil,    15,    14,    16,   nil,   nil,   nil,   nil,    17,   nil,
    18 ]

racc_action_check = [
     7,    45,     7,     7,    46,     7,     7,     7,     7,     7,
    60,    47,     7,    43,     7,    32,     7,    51,     7,     7,
     7,     7,    58,    60,    58,    58,    49,    58,    58,    58,
    58,    58,    50,    32,    58,    51,    58,    41,    58,    52,
    58,    58,    58,    58,    17,    53,    17,    17,     0,     0,
    73,    17,    73,    73,    17,    57,    17,    73,    54,    57,
    73,    56,     0,    39,    17,    59,    90,    37,    90,    90,
    73,    90,    30,    90,    90,    90,    28,    68,    90,    27,
    90,    11,    90,    11,    11,    90,    11,    24,    11,    11,
    11,    71,    21,    11,    15,    11,    78,    11,    78,    78,
    11,    78,    77,    78,    78,    78,    12,    82,    78,    83,
    78,    18,    78,    18,    18,    78,    18,    84,    18,    18,
    18,     8,    96,    18,    99,    18,     6,    18,    18,    72,
    18,    72,    72,   102,    72,   103,    72,    72,    72,     1,
   106,   107,   109,    72,    70,    72,    70,    70,    72,    70,
   111,    70,    70,    70,    44,   113,   nil,   nil,    70,    69,
    70,    69,    69,    70,    69,   nil,    69,    69,    69,   nil,
   nil,   nil,   nil,    69,    67,    69,    67,    67,    69,    67,
   nil,    67,    67,    67,   nil,   nil,   nil,   nil,    67,    62,
    67,    62,    62,    67,    62,   nil,    62,    62,    62,   nil,
   nil,    62,   nil,    62,   nil,    62,   nil,    62,    62,    31,
   nil,    31,    31,   nil,    31,   nil,    31,    31,    31,   nil,
   nil,    31,   nil,    31,    48,    31,    48,    48,    31,    48,
   nil,    48,    48,    48,   nil,   nil,    48,   nil,    48,   105,
    48,   105,   105,    48,   105,   nil,   105,   105,   105,   nil,
   nil,   nil,   nil,   105,     5,   105,     5,     5,   105,     5,
   nil,     5,     5,     5,   nil,   nil,     5,   nil,     5,   101,
     5,   101,   101,     5,   101,   nil,   101,   101,   101,   nil,
   nil,   101,   nil,   101,    33,   101,    33,    33,   101,    33,
   nil,    33,    33,    33,   nil,   nil,    33,   nil,    33,    34,
    33,    34,    34,    33,    34,   nil,    34,    34,    34,   nil,
   nil,    34,   nil,    34,    38,    34,    38,    38,    34,    38,
   nil,    38,    38,    38,   nil,   nil,   nil,   nil,    38,    40,
    38,    40,    40,    38,    40,   nil,    40,    40,    40,   nil,
   nil,    40,   nil,    40,    13,    40,    13,    13,    40,    13,
   nil,    13,    13,    13,   nil,   nil,   nil,   nil,    13,   nil,
    13 ]

racc_action_pointer = [
    43,   139,   nil,   nil,   nil,   247,   107,    -7,   121,   nil,
   nil,    74,   102,   337,   nil,    65,   nil,    37,   104,   nil,
   nil,    78,   nil,   nil,    67,   nil,   nil,    77,    62,   nil,
    70,   202,     4,   277,   292,   nil,   nil,    47,   307,    59,
   322,    26,   nil,     5,   146,   -13,    -4,     9,   217,     4,
    10,     6,    37,    21,    34,   nil,    39,    34,    15,    47,
    -4,   nil,   182,   nil,   nil,   nil,   nil,   167,    47,   152,
   137,    69,   122,    43,   nil,   nil,   nil,    83,    89,   nil,
   nil,   nil,   104,    90,    96,   nil,   nil,   nil,   nil,   nil,
    59,   nil,   nil,   nil,   nil,   nil,   114,   nil,   nil,   122,
   nil,   262,   111,   116,   nil,   232,   126,   127,   nil,   120,
   nil,   139,   nil,   137,   nil,   nil ]

racc_action_default = [
   -63,   -63,    -1,    -2,    -3,   -63,   -63,   -11,   -63,    -4,
   -33,   -63,   -46,   -63,   -50,   -51,   -52,   -37,   -63,   -59,
   -60,   -63,   -62,    -5,   -63,   -12,   -13,   -14,   -17,   -20,
   -21,   -63,   -51,   -63,   -63,   -27,   116,   -63,   -63,   -48,
   -63,   -63,   -38,   -63,   -63,   -63,   -63,   -43,   -63,   -63,
   -63,   -51,   -35,   -63,   -63,   -57,   -63,   -30,   -63,   -19,
   -63,   -22,   -63,   -25,   -26,   -34,   -47,   -63,   -63,   -63,
   -63,   -63,   -63,   -37,   -44,   -54,   -58,   -63,   -63,   -55,
   -56,   -61,   -63,   -63,   -63,   -15,   -16,   -18,   -23,   -24,
   -63,   -29,   -49,   -53,   -39,   -40,   -63,   -42,   -45,    -9,
   -36,   -63,   -63,   -63,   -28,   -63,   -63,    -6,   -31,   -63,
   -41,   -63,   -10,    -7,   -32,    -8 ]

racc_goto_table = [
     2,     9,    54,    35,    66,    50,    23,    37,    42,    53,
    39,    25,    26,     3,     4,    24,    82,    49,    89,     1,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    61,   nil,    63,
    64,    68,   nil,    92,   nil,    94,    95,   nil,    97,   nil,
   nil,   nil,   nil,   nil,    74,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    35,   nil,   nil,   nil,    91,   nil,
   nil,    98,    85,    86,    42,    88,   nil,   nil,   nil,   100,
   nil,   110,   nil,   nil,   nil,   nil,   nil,    99,   nil,   nil,
   nil,   nil,   nil,   102,   nil,   nil,   104,   nil,   nil,   nil,
   112,   nil,   nil,   nil,   nil,   nil,   nil,   107,   nil,   nil,
   nil,   nil,   nil,   109 ]

racc_goto_check = [
     2,     5,     8,     5,    15,    18,     2,     5,    13,    16,
    19,     9,    10,     3,     4,     6,     7,     2,    14,     1,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,     5,
     5,    16,   nil,    15,   nil,    15,    15,   nil,    15,   nil,
   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,     5,   nil,
   nil,    18,     9,    10,    13,    10,   nil,   nil,   nil,    16,
   nil,    15,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,
   nil,   nil,   nil,     2,   nil,   nil,     5,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,
   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,    19,     0,    13,    14,    -4,     8,   -41,   -16,     4,
     5,   nil,   nil,    -9,   -44,   -34,    -9,   nil,   -12,    -3 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    52,   nil,   nil,   nil,   nil,
   nil,    27,    28,    30,   nil,    10,   nil,    47,   nil,    12 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 33, :_reduce_1,
  1, 33, :_reduce_2,
  1, 33, :_reduce_3,
  2, 35, :_reduce_4,
  2, 36, :_reduce_5,
  6, 34, :_reduce_6,
  7, 34, :_reduce_7,
  8, 34, :_reduce_8,
  3, 40, :_reduce_9,
  5, 40, :_reduce_10,
  0, 38, :_reduce_11,
  1, 38, :_reduce_12,
  1, 38, :_reduce_13,
  1, 41, :_reduce_14,
  3, 41, :_reduce_15,
  3, 41, :_reduce_16,
  1, 43, :_reduce_17,
  3, 43, :_reduce_18,
  2, 43, :_reduce_19,
  1, 43, :_reduce_20,
  1, 42, :_reduce_21,
  2, 42, :_reduce_22,
  3, 42, :_reduce_23,
  3, 45, :_reduce_24,
  2, 44, :_reduce_25,
  2, 44, :_reduce_26,
  1, 44, :_reduce_27,
  2, 46, :_reduce_28,
  1, 46, :_reduce_29,
  0, 39, :_reduce_30,
  3, 39, :_reduce_31,
  4, 39, :_reduce_32,
  1, 37, :_reduce_33,
  3, 37, :_reduce_34,
  1, 48, :_reduce_35,
  3, 48, :_reduce_36,
  0, 49, :_reduce_none,
  1, 49, :_reduce_38,
  3, 49, :_reduce_39,
  3, 49, :_reduce_40,
  5, 49, :_reduce_41,
  3, 49, :_reduce_42,
  1, 50, :_reduce_43,
  2, 50, :_reduce_44,
  3, 50, :_reduce_45,
  1, 47, :_reduce_46,
  3, 47, :_reduce_47,
  2, 47, :_reduce_48,
  4, 47, :_reduce_49,
  1, 51, :_reduce_50,
  1, 51, :_reduce_51,
  1, 51, :_reduce_52,
  4, 51, :_reduce_53,
  3, 51, :_reduce_54,
  3, 51, :_reduce_55,
  3, 51, :_reduce_56,
  2, 51, :_reduce_57,
  3, 51, :_reduce_58,
  1, 51, :_reduce_59,
  1, 51, :_reduce_60,
  3, 51, :_reduce_61,
  1, 51, :_reduce_62 ]

racc_reduce_n = 63

racc_shift_n = 116

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :RARROW => 3,
  :OR => 4,
  :HASH_TYPE => 5,
  :HASH_QUERY => 6,
  :CONST_BEGIN => 7,
  :RASSOC => 8,
  :FIXNUM => 9,
  :FLOAT => 10,
  :COLON => 11,
  :DOT => 12,
  :DOTS => 13,
  :ID => 14,
  :SYMBOL => 15,
  :SPECIAL_ID => 16,
  :STRING => 17,
  :PREDICATE => 18,
  :LPAREN => 19,
  :RPAREN => 20,
  :LBRACE => 21,
  :RBRACE => 22,
  :LBRACKET => 23,
  :RBRACKET => 24,
  :QUERY => 25,
  :BANG => 26,
  :STARSTAR => 27,
  :STAR => 28,
  :LESS => 29,
  :GREATER => 30,
  :EOF => 31 }

racc_nt_base = 32

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "RARROW",
  "OR",
  "HASH_TYPE",
  "HASH_QUERY",
  "CONST_BEGIN",
  "RASSOC",
  "FIXNUM",
  "FLOAT",
  "COLON",
  "DOT",
  "DOTS",
  "ID",
  "SYMBOL",
  "SPECIAL_ID",
  "STRING",
  "PREDICATE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "QUERY",
  "BANG",
  "STARSTAR",
  "STAR",
  "LESS",
  "GREATER",
  "EOF",
  "$start",
  "entry",
  "method_type",
  "bare_type",
  "query_type",
  "type_expr",
  "arg_list",
  "block",
  "method_sig_list",
  "nonempty_arg_list",
  "named_arg_list",
  "arg",
  "base_arg",
  "named_arg",
  "base_arg_query_only",
  "union_type",
  "type_expr_comma_list",
  "hash_expr",
  "hash_expr_comma_list",
  "single_type" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_1(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 20)
  def _reduce_3(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_4(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 26)
  def _reduce_5(val, _values, result)
     result = RDL::Type::MethodType.new val[1].args, val[1].block, val[1].ret 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 30)
  def _reduce_6(val, _values, result)
            result = RDL::Type::MethodType.new val[1], val[3], val[5]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 33)
  def _reduce_7(val, _values, result)
            result = RDL::Type::MethodType.new val[1], val[3], RDL::Type::AnnotatedArgType.new(val[6], val[5])
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_8(val, _values, result)
            result = RDL::Type::MethodType.new val[1], val[3], RDL::Type::DependentArgType.new(val[6], val[5], val[7])
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 40)
  def _reduce_9(val, _values, result)
     result = [val[0].to_sym, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 41)
  def _reduce_10(val, _values, result)
     result = [val[0].to_sym, val[2]] + val[4] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 44)
  def _reduce_11(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 45)
  def _reduce_12(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 47)
  def _reduce_13(val, _values, result)
          result = [RDL::Type::FiniteHashType.new(Hash[*val[0][0]], val[0][1])]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 50)
  def _reduce_14(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 51)
  def _reduce_15(val, _values, result)
     result = val[2].unshift val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 52)
  def _reduce_16(val, _values, result)
     # named arg list must come last
      result = [val[0], RDL::Type::FiniteHashType.new(Hash[*val[2][0]], val[2][1])]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 56)
  def _reduce_17(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 57)
  def _reduce_18(val, _values, result)
     result = RDL::Type::DependentArgType.new(val[1], val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 58)
  def _reduce_19(val, _values, result)
     result = RDL::Type::AnnotatedArgType.new(val[1], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 59)
  def _reduce_20(val, _values, result)
     result = RDL::Type::DotsQuery.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 61)
  def _reduce_21(val, _values, result)
     result = [val[0], nil] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 62)
  def _reduce_22(val, _values, result)
     result = [[], val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 63)
  def _reduce_23(val, _values, result)
     result = [val[0] + val[2][0], val[2][1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 65)
  def _reduce_24(val, _values, result)
     result = [val[0].to_sym, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_25(val, _values, result)
     result = RDL::Type::OptionalType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 69)
  def _reduce_26(val, _values, result)
     result = RDL::Type::VarargType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 70)
  def _reduce_27(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 72)
  def _reduce_28(val, _values, result)
     result = RDL::Type::OptionalType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 73)
  def _reduce_29(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 76)
  def _reduce_30(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 77)
  def _reduce_31(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_32(val, _values, result)
     result = RDL::Type::OptionalType.new val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_33(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 82)
  def _reduce_34(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_35(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_36(val, _values, result)
     result = [val[0]] + val[2] 
    result
  end
.,.,

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.racc', 89)
  def _reduce_38(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 90)
  def _reduce_39(val, _values, result)
     result = [val[0].to_i, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 91)
  def _reduce_40(val, _values, result)
     result = [val[0].to_f, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_41(val, _values, result)
        result = [Kernel.const_get(val[0]), val[2]]
  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 95)
  def _reduce_42(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 98)
  def _reduce_43(val, _values, result)
     result = [val[0], nil] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 99)
  def _reduce_44(val, _values, result)
     result = [[], val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_45(val, _values, result)
     result = [val[0] + val[2][0], val[2][1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 103)
  def _reduce_46(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 104)
  def _reduce_47(val, _values, result)
     result = RDL::Type::UnionType.new val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 105)
  def _reduce_48(val, _values, result)
     result = RDL::Type::NonNullType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 106)
  def _reduce_49(val, _values, result)
     result = RDL::Type::UnionType.new(RDL::Type::NonNullType.new(val[1]), val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 109)
  def _reduce_50(val, _values, result)
     result = RDL::Type::SingletonType.new(val[0].to_sym) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 111)
  def _reduce_51(val, _values, result)
          if val[0] == 'nil' then
        result = $__rdl_nil_type
      elsif val[0] == 'true' then
        result = $__rdl_true_type
      elsif val[0] == 'false'
        result = $__rdl_false_type
      elsif val[0] =~ /^[a-z_]+\w*\'?/ then
        result = RDL::Type::VarType.new(val[0].to_sym)
      else
        result = RDL::Type::NominalType.new val[0]
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 124)
  def _reduce_52(val, _values, result)
          if $__rdl_special_types.has_key? val[0] then
        result = $__rdl_special_types[val[0]]
      else
        fail "Unexpected special type identifier #{val[0]}"
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 131)
  def _reduce_53(val, _values, result)
          n = RDL::Type::NominalType.new(val[0])
      result = RDL::Type::GenericType.new(n, *val[2])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 134)
  def _reduce_54(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 136)
  def _reduce_55(val, _values, result)
          result = RDL::Type::TupleType.new(*val[1])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 139)
  def _reduce_56(val, _values, result)
          result = RDL::Type::StructuralType.new(Hash[*val[1]])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 142)
  def _reduce_57(val, _values, result)
          result = RDL::Type::TupleType.new
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 145)
  def _reduce_58(val, _values, result)
          result = RDL::Type::FiniteHashType.new(Hash[*val[1][0]], val[1][1])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 147)
  def _reduce_59(val, _values, result)
     result = RDL::Type::SingletonType.new(val[0].to_i) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 148)
  def _reduce_60(val, _values, result)
     result = RDL::Type::SingletonType.new(val[0].to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 150)
  def _reduce_61(val, _values, result)
          result =  RDL::Type::SingletonType.new(Kernel.const_get(val[1]))
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 154)
  def _reduce_62(val, _values, result)
     result = RDL::Type::WildQuery.new 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser


end
