class Pathname
  type 'self.getwd', '() -> Pathname'
  type 'self.glob', '(p1: String, p2: ?String) -> Array<Pathname>'
  type 'self.new', '(p1: String) -> Pathname' # p1 can be String-like
  rdl_alias 'self.pwd', 'self.getwd'
  type :+, '(other: String or Pathname) -> Pathname'
  rdl_alias :/, :+
  type :<=>, '(p1: %any) -> -1 or 0 or 1 or nil'
  type :==, '(p1: %any) -> %bool'
  type :===, '(p1: %any) -> %bool'
  type :absolute?, '() -> %bool'
  type :ascend, '() { (Pathname) -> %any } -> %any'
  type :atime, '() -> Time'
  type :basename, '(p1: ?String) -> Pathname' # guessing about arg type
  type :binread, '(length: ?Fixnum, offset: ?Fixnum) -> String'
  type :binwrite, '(String, offset: ?Fixnum) -> Fixnum' # TODO open_args
  type :birthtime, '() -> Time'
  type :blockdev?, '() -> %bool'
  type :chardev?, '() -> %bool'
  type :children, '(with_directory: %bool) -> Array<Pathname>'
  type :chmod, '(mode: Fixnum) -> Fixnum'
  type :chown, '(owner: Fixnum, group: Fixnum) -> Fixnum'
  type :cleanpath, '(consider_symlink: %bool) -> %any'
  type :ctime, '() -> Time'
  type :delete, '() -> %any'
  type :descend, '() { (Pathname) -> %any } -> %any'
  type :directory?, '() -> %bool'
  type :dirname, '() -> Pathname'
  type :each_child, '(with_directory: %bool) { (Pathname) -> %any } -> %any'
  type :each_entry, '() { (Pathname) -> %any } -> %any'
  type :each_filename, '() { (String) -> %any } -> %any'
  type :each_filename, '() -> Enumerator<String>'
  type :each_line, '(sep: ?String, limit: ?Fixnum) { (String) -> %any } -> %any' # TODO open_args
  type :each_line, '(sep: ?String, limit: ?Fixnum) -> Enumerator<String>'
  type :entries, '() -> Array<Pathname>'
  type :eql?, '(%any) -> %bool'
  type :executable?, '() -> %bool'
  type :executable_real?, '() -> %bool'
  type :exist?, '() -> %bool'
  type :expand_path, '(p1: ?(String or Pathname)) -> Pathname'
  type :extname, '() -> String'
  type :file?, '() -> %bool'
  type :find, '(ignore_error: %bool) { (Pathname) -> %any } -> %any'
  type :find, '(ignore_error: %bool) -> Enumerator<Pathname>'
  type :fnmatch, '(pattern: String, flags: ?Fixnum) -> %bool'
  type :freeze, '() -> self' # TODO return type?
  type :ftype, '() -> String'
  type :grpowned?, '() -> %bool'
  type :join, '(args: *String) -> Pathname'
  type :lchmod, '(mode: Fixnum) -> Fixnum'
  type :lchown, '(owner: Fixnum, group: Fixnum) -> Fixnum'
  type :lstat, '() -> File::Stat'
  type :make_link, '(old: String) -> 0'
  type :symlink, '(old: String) -> 0'
  type :mkdir, '(p1: String) -> 0'
  type :mkpath, '() -> %any' # TODO return?
  type :mountpoint?, '() -> %bool'
  type :mtime, '() -> Time'
  type :open, '(mode: ?String, perm: ?String, opt: ?Fixnum) -> File'
  type :open, '(mode: ?String, perm: ?String, opt: ?Fixnum) { (File) -> t } -> t'
  type :opendir, '(?Encoding) -> Dir'
  type :opendir, '(?Encoding) { (Dir) -> u } -> u'
  type :owned?, '() -> %bool'
  type :parent, '() -> Pathname'
  type :pipe?, '() -> %bool'
  type :read, '(length: ?Fixnum, offset: ?Fixnum, open_args: ?Fixnum) -> String'
  type :readable?, '() -> %bool'
  type :readable_real, '() -> %bool'
  type :readlines, '(sep: ?String, limit: ?Fixnum, open_args: ?Fixnum) -> Array<String>'
  type :readlink, '() -> file: String'
  type :realdirpath, '(p1: ?String) -> String'
  type :realpath, '(p1: ?String) -> String'
  type :relative?, '() -> %bool'
  type :relative_path_from, '(base_directory: String) -> String'
  type :rename, '(p1: String) -> 0'
  type :rmdir, '() -> 0'
  type :rmtree, '() -> 0'
  type :root?, '() -> %bool'
  type :setgid?, '() -> %bool'
  type :setuid?, '() -> %bool'
  type :size, '() -> Fixnum'
  type :size?, '() -> %bool'
  type :socket?, '() -> %bool'
  type :split, '() -> [String, String]'
  type :stat, '() -> File::Stat'
  type :sticky?, '() -> %bool'
  type :sub, '(args: *String) -> Pathname'
  type :sub_ext, '(p1: String) -> Pathname'
  type :symlink?, '() -> %bool'
  type :sysopen, '(mode: ?Fixnum, perm: ?Fixnum) -> Fixnum'
  type :taint, '() -> self'
  type :to_path, '() -> String'
  rdl_alias :to_s, :to_path
  type :truncate, '(length: Fixnum) -> 0'
  type :unlink, '() -> Fixnum'
  type :untaint, '() -> self'
  type :utime, '(atime: Time, mtime: Time) -> Fixnum'
  type :world_readable?, '() -> %bool'
  type :world_writable?, '() -> %bool'
  type :writable?, '() -> %bool'
  type :writable_real?, '() -> %bool'
  type :write, '(String, offset: ?Fixnum, open_args: ?Fixnum) -> Fixnum'
  type :zero?, '() -> %bool'
end