class Rational
  type :*, '(Numeric) -> Numeric'
  type :**, '(Numeric) -> Numeric'
  type :+, '(Numeric) -> Numeric'
  type :-, '(Numeric) -> Numeric'
  type :/, '(Numeric) -> Numeric'
  type :<=>, '(Numeric) -> -1 or 0 or 1 or nil'
  type :==, '(object: %any) -> %bool'
  type :ceil, '() -> Integer'
  type :ceil, '(precision: Fixnum) -> Rational'
  type :denominator, '() -> Integer'
  post(:denominator) { |r, _| r > 0 }
  type :fdiv, '(Numeric) -> Float'
  type :floor, '() -> Integer'
  type :floor, '(precision: Fixnum) -> Rational'
  type :inspect, '() -> String'
  type :numerator, '() -> Integer'
  rdl_alias :quo, :/
  type :rationalize, '() -> self'
  type :rationalize, '(eps: Numeric) -> Rational'
  type :round, '() -> Integer'
  type :round, '(precision: Fixnum) -> Rational'
  type :to_f, '() -> Float'
  type :to_i, '() -> Integer'
  type :to_r, '() -> self'
  type :to_s, '() -> String'
  type :truncate, '() -> Integer'
  type :truncate, '(precision: Fixnum) -> Rational'
end