['generic.rb',
 'intersection.rb',
 'method.rb',
 'nil.rb',
 'named.rb',
 'optional.rb',
 'structural.rb',
 'top.rb',
 'tuple.rb',
 'type.rb',
 'union.rb',
 'vararg.rb'].each { |f| require_relative f }
