rdl_nowrap :'ActionView::Helpers::UrlHelper'
type :'ActionView::Helpers::UrlHelper', :link_to, '(String, String or ActiveRecord::Base, ?Hash<Symbol, %any>) -> ActiveSupport::SafeBuffer'
type :'ActionView::Helpers::UrlHelper', :link_to, '(String, ?Hash<Symbol, %any>, ?Hash<Symbol, %any>) -> ActiveSupport::SafeBuffer'
type :'ActionView::Helpers::UrlHelper', :link_to, '(?Hash<Symbol, %any>, ?Hash<Symbol, %any>) {() -> String} -> ActiveSupport::SafeBuffer'
type :'ActionView::Helpers::UrlHelper', :link_to, '(?String, ?Hash<Symbol, %any>) {() -> String} -> ActiveSupport::SafeBuffer'
